// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tajcajkjxbjqpbrhvxdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhamNhamtqeGJqcXBicmh2eGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTk4NDIsImV4cCI6MjA2MDE5NTg0Mn0.iUeSClVhNCL_YDuLJd03NVqDqPJs_QuQwRPndwv_NKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);